using System.Collections;
using UnityEngine;
using UnityEngine.AI;

[RequireComponent(typeof(Animator), typeof(NavMeshAgent))]
public class UnityChanController : MonoBehaviour
{

    public Vector3 destination;
    [SerializeField] private Animator unityChanAnimator;
    [SerializeField] private NavMeshAgent navMeshAgent;

    #region -- 戈方把σ跋 --

    #endregion

    #region -- 跑计把σ跋 --

    private bool hasNecessaryComponent = true;

    #endregion

    #region -- 飑lて/B@ --

    private void Awake()
    {

        if(CheckNecessaryComponent()) hasNecessaryComponent = false;

    }

    private void Update()
    {

        if (!hasNecessaryComponent) return;

        NavMeshAgentSpeedToAnimator();

    }

    #endregion

    #region -- よk把σ跋 --

    /// <summary>
    /// T{ゲn舱ンO_ゼ窀mAゼ窀m^肚true
    /// </summary>
    private bool CheckNecessaryComponent()
    {
        if (navMeshAgent == null)
        {
            Debug.LogError("ゼf更navMeshAgent");
            return true;
        }
        if (unityChanAnimator == null)
        {
            Debug.LogError("ゼf更Animator");
            return true;
        }

        return false;
    }

    private void NavMeshAgentSpeedToAnimator()
    {
        unityChanAnimator.SetFloat("Speed", navMeshAgent.speed);
    }

    /// <summary>
    /// ]wNavMeashAgent亥鬲害a
    /// </summary>
    public void SetDestination(Vector3 value)
    {
        destination = value;
        if (navMeshAgent != null)
            navMeshAgent.SetDestination(destination);
        else Debug.LogError("ゼf更navMeshAgent");
    }

    /// <summary>
    /// H诀]wNavMeashAgent撼t
    /// </summary>
    public IEnumerator RandomChangeSpeed()
    {
        int navMeshAgentSpeed = Random.Range(0, 10);
        navMeshAgent.speed = navMeshAgentSpeed;
        navMeshAgent.avoidancePriority = 50;

        if (navMeshAgentSpeed == 0)
        {
            navMeshAgent.avoidancePriority = 1;
            int waitTime = Random.Range(5, 30);
            if (waitTime > 5) unityChanAnimator.SetBool("Rest", true);

            yield return new WaitForSeconds(waitTime);

            if (waitTime > 5) unityChanAnimator.SetBool("Rest", false);
            StartCoroutine(RandomChangeSpeed());
        }
    }

    #endregion
}
